### ISSUE TITLE
Trouble migrating to 3.13.0

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/toil#2035]
I'm trying to upgrade from 3.11.0 to 3.13.0, but some of my scripts don't work with the new version.  Specifically, I'm able to create a leader node, but when I launch my script, it gets stuck in the loop below.  The worker gets created, but nothing runs on it (docker ps gives blank).  This is the type of behaviour I've seen before when forgetting to set --mesosMaster but it seems correctly set (identical scripts working fine with 3.11.0).  

Are there any interface changes in the new version that could cause this? 

```
Currently 1 nodes of type r3.8xlarge in cluster
DEBUG:toil.provisioners.clusterScaler:Difference in new (1) and previous estimates in number of r3.8xlarge (1) required is within beta (1.2), making no change.
DEBUG:toil.provisioners.aws.awsProvisioner:All nodes in cluster: [Instance:i-04b3b54e4f73fb7b3, Instance:i-05afa50cf5334b470]
DEBUG:toil.provisioners.aws.awsProvisioner:All workers found in cluster: [Instance:i-04b3b54e4f73fb7b3]
DEBUG:toil.provisioners.aws.awsProvisioner:non-preemptable workers found in cluster: [Instance:i-04b3b54e4f73fb7b3]
DEBUG:toil.provisioners.clusterScaler:Consolidating state between mesos and provisioner
DEBUG:toil.provisioners.clusterScaler:Worker node at 172.31.30.237 is not reporting executor information
INFO:toil.provisioners.clusterScaler:There are 0 nodes being ignored by the batch system, checking if they can be terminated
```

Relevant Toil options

     --logDebug --provisioner aws --nodeTypes r3.8xlarge:0.85 --defaultPreemptable --maxNodes 8 --retryCount 3 --realTimeLogging --logDebug --batchSystem=mesos --mesosMaster=172.31.23.216:5050

**Comment by DailyDreaming** [comment]
It's the docker image most likely.  Just put a new one up and am testing it right now.  In the meantime, 3.12.0 was tested and should be working.

**Comment by joelarmstrong** [comment]
Not sure the new 3.13.0 docker image will work, [it's setting](https://quay.io/repository/ucsc_cgl/toil/image/e0fd3c5788fca67fd763691e799ee68f7f46f1145d1a25577b2b1eae0a62dee5) `TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:3.14.0a1.dev12345-f67f4d5a3c0803a6c8c95e7ca6a5ad7b4c6e5735` which doesn't seem to exist.

How are we handling container building/tagging for the releases? We used to build/tag for every commit, and it looks like after that was turned off we started having container problems on every release.

**Comment by glennhickey** [comment]
I haven't had much luck with 3.13.0 either FWIW.  I tried using
`TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:3.13.0` both when creating my
leader and when launching my script and I still have the same problem.

**Comment by joelarmstrong** [comment]
If you're setting TOIL_APPLIANCE_SELF when you're launching the workflow then yeah, it looks like the container probably isn't the problem.

Can you dump /var/lib/mesos/mesos-master.INFO from the leader?

**Comment by DailyDreaming** [comment]
3.13.0 should be fixed now if you want to try it.

**Comment by glennhickey** [comment]
Should have had this in my original post, but when never specifying the
appliance, the leader gets made with

quay.io/ucsc_cgl/toil:3.13.0-3cb535425306955028ed7604114f772990d00440

and the worker gets made with

quay.io/ucsc_cgl/toil:3.13.0-3cb535425306955028ed7604114f772990d00440-dirty

The mesos-master dump from this version is attached (cc'ing you, joel if
github eats it).

Will repeat the exercise with 3.13.0 again.

**Comment by joelarmstrong** [comment]
Interesting. The mesos master did get a connection to the slave at 172.31.18.105:5051, and it ran a few tasks just fine. It looks fairly normal. So mesosMasterAddress doesn't seem to be a problem, at least.

Does the toil log indicate that the tasks were issued/finished, or not? Maybe this problem only starts when certain jobs are run.

**Comment by glennhickey** [comment]
Boy, it actually did work.  While I was in another tab pasting the mesos
log, by first job kicked in about 3 minutes after the first "Worker node is
not reporting executor information" message.

I'm sure I had let it run at least 5-10 minutes before positing my initial
complaint.  Maybe it's just the logging or me being on crack, or could it
be that this version takes longer to start?

**Comment by joelarmstrong** [comment]
All of the above? :) I think it's possible that it just took way longer to start than normal. Sometimes I've seen Quay throttling us (because we're on the free tier), which can make nodes take much longer to start up properly.

**Comment by glennhickey** [comment]
Thanks Joel and Daily, and sorry for the noise.  I just ran again
specifying 3.13.0 and it ran fine after a 6 minute wait.
