### ISSUE TITLE
cwl dynamic resource requirement bug

### ISSUE THREAD

**Issue by pkp124** [BD2KGenomics/toil#2048]
I am trying use the dynamic resource requirement feature in gridEngine which was merged in #1810 and found an issue. 
To reproduce the issue, please add the below lines to toil/src/toil/test/cwl/revtool.cwl  and run "cwltoil --no-container --retryCount 0  --batchSystem gridEngine revsort.cwl revsort-job.json"
``` cwl
requirements:
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    ramMin: $(inputs.input.size)
```

Below is the worker log for sorttool

```python
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.13.0-3cb535425306955028ed7604114f772990d00440.
Traceback (most recent call last):
  File "/work/toil/src/toil/worker.py", line 301, in main
    job = Job._loadJob(jobGraph.command, jobStore)
  File "/work/toil/src/toil/job.py", line 902, in _loadJob
    return cls._unpickle(userModule, fileHandle, jobStore.config)
  File "/work/toil/src/toil/job.py", line 931, in _unpickle
    runnable = unpickler.load()
  File "/work/toil/src/toil/job.py", line 1735, in __new__
    return cls._resolve(*args)
  File "/work/toil/src/toil/job.py", line 1747, in _resolve
    value = pickle.load(fileHandle)
  File "/work/toil/src/toil/job.py", line 1735, in __new__
    return cls._resolve(*args)
  File "/work/toil/src/toil/job.py", line 1747, in _resolve
    value = pickle.load(fileHandle)
  File "/work/toil/src/toil/job.py", line 1827, in __setstate__
    "this job as a child/follow-on of {jobName}.".format(jobName=jobName))
RuntimeError: (RuntimeError(RuntimeError("This job was passed a promise that wasn't yet resolved when it ran. The job 'file:///work/toil/src/toil/test/cwl/revtool.cwl' rev that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'file:///work/toil/src/toil/test/cwl/revtool.cwl' rev. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'file:///work/toil/src/toil/test/cwl/revtool.cwl' rev.",), <class 'toil.job.Promise'>, (u'file:/tmp/tmp14goWU', 'N/u/tmpF1_VvA.tmp')), <class 'toil.job.Promise'>, (u'file:/tmp/tmp14goWU', 'O/g/tmp_Mr8W3.tmp'))
ERROR:toil.worker:Exiting the worker because of a failed job on host host01
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'file:///work/toil/src/toil/test/cwl/sorttool.cwl' sort J/b/jobhOqgt1 with ID J/b/jobhOqgt1 to 0

```

As per my understanding, there are two steps revtool and sorttool in the revsort workflow. Two wrapper jobs are created for both of them. The revtool_wrapper spawns the actual revtool job, but also sorttool_wrapper job is started. Since sorttool wrapper does not have its promise fulfilled the workflow fails.

**Comment by mr-c** [comment]
Hello @pkp124 and thank you for your report. Is this reproducible using the latest dev version of Toil? 

http://toil.readthedocs.io/en/3.12.0/gettingStarted/install.html#building-from-source

**Comment by pkp124** [comment]
Hello @mr-c , thanks for the quick response. I was able to reproduce the same issue on the latest commit of the master branch, although i had to rerun multiple times (~ 10) to reproduce the issue.

**Comment by mr-c** [comment]
@pkp124 Thanks. I am also now able to reproduce and I will continue my investigation.

**Comment by mr-c** [comment]
@pkp124 Does https://github.com/BD2KGenomics/toil/pull/2049 work for you?

**Comment by mr-c** [comment]
@pkp124 I think we fixed it! Thanks again for alerting me to this issue and for the easy to reproduce example; that was very helpful.

**Comment by pkp124** [comment]
@mr-c , thanks for the effort. I did some quick tests today and unfortunately, found that the error still persists :)  Again, the issue can be reproduced with the same files, by running multiple times.

**Comment by mr-c** [comment]
Okay, @DailyDreaming @ejacox and others, I need your help.

When in toil-cwl-runner we have dynamic resource requirements we add a CWLJobWrapper to the job graph so we can attach the real job with the current memory, cpu, and disk requirements once the inputs are known.

In an attempt to address this issue I added a follow on link between the existing children of the CWLJobWrapper and the new "real" job:

https://github.com/BD2KGenomics/toil/blob/ad1a097f45d5019540972da36d44a805b1104b72/src/toil/cwl/cwltoil.py#L400

Seems like this isn't enough. Any suggestions?

**Comment by pkp124** [comment]
One thing I noticed, the CWLJobWrapper does not seem to have any children.

**Comment by mr-c** [comment]
@pkp124 Yes, and it is missing the reference to its predecessors as well. Perhaps a pickling error?

**Comment by mr-c** [comment]
To be fair, I was using a non-public member of `Job`; seems that accessing the children is not a feature of Toil right now: https://github.com/BD2KGenomics/toil/blob/ad1a097f45d5019540972da36d44a805b1104b72/src/toil/job.py#L1092

However, we can modify the Workflow runner to make the descendants of the CWLJobWrapper as "follow ons" and not "children": https://github.com/BD2KGenomics/toil/pull/2053

**Comment by pkp124** [comment]
Not sure about this, but, couldn't all the jobs be followOns regardless of wrapper or not?

**Comment by mr-c** [comment]
@pkp124 Possibly, but I don't know all the consequences of that, so I'm trying to make minimal changes
